// flow-typed signature: b16a58ddba20acba75181dbc20478f3b
// flow-typed version: <<STUB>>/react-static_v7.1.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-static/babel-preset' {
  declare module.exports: any;
}

declare module 'react-static/lib/bootstrapApp' {
  declare module.exports: any;
}

declare module 'react-static/lib/bootstrapPlugins' {
  declare module.exports: any;
}

declare module 'react-static/lib/bootstrapTemplates' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/components/Default404' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/components/Root' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/components/RouteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/components/Routes' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/components/SiteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/context/routePathContext' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/context/staticInfoContext' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/useBasepath' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/useLocation' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/usePrefetch' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/useRouteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/useRoutePath' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/useSiteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/hooks/useStaticInfo' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/utils/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/utils/onLocationChange' {
  declare module.exports: any;
}

declare module 'react-static/lib/browser/utils/Visibility' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/build' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/bundle' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/create' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/export' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/start' {
  declare module.exports: any;
}

declare module 'react-static/lib/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/index.node' {
  declare module.exports: any;
}

declare module 'react-static/lib/node/getWebpackConfig' {
  declare module.exports: any;
}

declare module 'react-static/lib/node/makePageRoutes' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/configWithPluginWithOptions.mock' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/defaultConfigDevelopment.mock' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/defaultConfigProduction.mock' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/pages/404' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/pages/about' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/pages/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/__mocks__/static.config.mock' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/buildState' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/cleanProjectFiles' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/clientStats' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/components/BodyWithMeta' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/components/HeadWithMeta' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/components/HtmlWithMeta' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/components/Redirect' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/components/RootComponents' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/copyPublicFiles' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/createSharedData' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/exportRoute' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/exportRoutes' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/exportRoutes.sync' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/exportRoutes.threaded' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/exportSharedRouteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/extractTemplates' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/fetchRoutes' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/fetchSiteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/generateBrowserPlugins' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/generateTemplates' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/getConfig' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/getRouteData' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/getRoutes' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/plugins' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/buildProductionBundles' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/makeWebpackConfig' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/rules/cssLoader' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/rules/fileLoader' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/rules/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/rules/jsLoader' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/rules/jsLoaderExternal' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/runDevServer' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-static/lib/static/webpack/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils/binHelper' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils/chunkBuilder' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils/createIndexPlaceholder' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils/progress' {
  declare module.exports: any;
}

declare module 'react-static/node/index' {
  declare module.exports: any;
}

declare module 'react-static/setupTests' {
  declare module.exports: any;
}

declare module 'react-static/src/bootstrapApp' {
  declare module.exports: any;
}

declare module 'react-static/src/bootstrapPlugins' {
  declare module.exports: any;
}

declare module 'react-static/src/bootstrapTemplates' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/components/Default404' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/components/Root' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/components/RouteData' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/components/Routes' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/components/SiteData' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/context/routePathContext' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/context/staticInfoContext' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/useBasepath' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/useLocation' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/usePrefetch' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/useRouteData' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/useRoutePath' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/useSiteData' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/hooks/useStaticInfo' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/index' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/utils/__tests__/shared.test' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/utils/index' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/utils/onLocationChange' {
  declare module.exports: any;
}

declare module 'react-static/src/browser/utils/Visibility' {
  declare module.exports: any;
}

declare module 'react-static/src/commands/build' {
  declare module.exports: any;
}

declare module 'react-static/src/commands/bundle' {
  declare module.exports: any;
}

declare module 'react-static/src/commands/create' {
  declare module.exports: any;
}

declare module 'react-static/src/commands/export' {
  declare module.exports: any;
}

declare module 'react-static/src/commands/start' {
  declare module.exports: any;
}

declare module 'react-static/src/index' {
  declare module.exports: any;
}

declare module 'react-static/src/index.node' {
  declare module.exports: any;
}

declare module 'react-static/src/node/getWebpackConfig' {
  declare module.exports: any;
}

declare module 'react-static/src/node/makePageRoutes' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/configWithPluginWithOptions.mock' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/defaultConfigDevelopment.mock' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/defaultConfigProduction.mock' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/pages/404' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/pages/about' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/pages/index' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/static.config.mock' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__mocks__/static.config.mock' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__tests__/getConfig.test' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__tests__/getRoutes.test' {
  declare module.exports: any;
}

declare module 'react-static/src/static/__tests__/webpack.test' {
  declare module.exports: any;
}

declare module 'react-static/src/static/buildState' {
  declare module.exports: any;
}

declare module 'react-static/src/static/cleanProjectFiles' {
  declare module.exports: any;
}

declare module 'react-static/src/static/clientStats' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/__tests__/BodyWithMeta.test' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/__tests__/HeadWithMeta.test' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/__tests__/HtmlWithMeta.test' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/BodyWithMeta' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/HeadWithMeta' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/HtmlWithMeta' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/Redirect' {
  declare module.exports: any;
}

declare module 'react-static/src/static/components/RootComponents' {
  declare module.exports: any;
}

declare module 'react-static/src/static/copyPublicFiles' {
  declare module.exports: any;
}

declare module 'react-static/src/static/createSharedData' {
  declare module.exports: any;
}

declare module 'react-static/src/static/exportRoute' {
  declare module.exports: any;
}

declare module 'react-static/src/static/exportRoutes' {
  declare module.exports: any;
}

declare module 'react-static/src/static/exportRoutes.sync' {
  declare module.exports: any;
}

declare module 'react-static/src/static/exportRoutes.threaded' {
  declare module.exports: any;
}

declare module 'react-static/src/static/exportSharedRouteData' {
  declare module.exports: any;
}

declare module 'react-static/src/static/extractTemplates' {
  declare module.exports: any;
}

declare module 'react-static/src/static/fetchRoutes' {
  declare module.exports: any;
}

declare module 'react-static/src/static/fetchSiteData' {
  declare module.exports: any;
}

declare module 'react-static/src/static/generateBrowserPlugins' {
  declare module.exports: any;
}

declare module 'react-static/src/static/generateTemplates' {
  declare module.exports: any;
}

declare module 'react-static/src/static/getConfig' {
  declare module.exports: any;
}

declare module 'react-static/src/static/getRouteData' {
  declare module.exports: any;
}

declare module 'react-static/src/static/getRoutes' {
  declare module.exports: any;
}

declare module 'react-static/src/static/plugins' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/buildProductionBundles' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/makeWebpackConfig' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/rules/cssLoader' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/rules/fileLoader' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/rules/index' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/rules/jsLoader' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/rules/jsLoaderExternal' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/runDevServer' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-static/src/static/webpack/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'react-static/src/utils/__tests__/chunkBuilder.test' {
  declare module.exports: any;
}

declare module 'react-static/src/utils/binHelper' {
  declare module.exports: any;
}

declare module 'react-static/src/utils/chunkBuilder' {
  declare module.exports: any;
}

declare module 'react-static/src/utils/createIndexPlaceholder' {
  declare module.exports: any;
}

declare module 'react-static/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-static/src/utils/progress' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/App' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/components/Router' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/containers/Dynamic' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/index' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/pages/404' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/pages/about' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/pages/blog' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/src/pages/index' {
  declare module.exports: any;
}

declare module 'react-static/templates/basic/static.config' {
  declare module.exports: any;
}

declare module 'react-static/templates/blank/src/App' {
  declare module.exports: any;
}

declare module 'react-static/templates/blank/src/index' {
  declare module.exports: any;
}

declare module 'react-static/templates/blank/static.config' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/App' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/index' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/pages/404' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/pages/about' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/pages/blog' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/src/pages/index' {
  declare module.exports: any;
}

declare module 'react-static/templates/stress-test/static.config' {
  declare module.exports: any;
}

declare module 'react-static/templates/typescript/static.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-static/babel-preset.js' {
  declare module.exports: $Exports<'react-static/babel-preset'>;
}
declare module 'react-static/lib/bootstrapApp.js' {
  declare module.exports: $Exports<'react-static/lib/bootstrapApp'>;
}
declare module 'react-static/lib/bootstrapPlugins.js' {
  declare module.exports: $Exports<'react-static/lib/bootstrapPlugins'>;
}
declare module 'react-static/lib/bootstrapTemplates.js' {
  declare module.exports: $Exports<'react-static/lib/bootstrapTemplates'>;
}
declare module 'react-static/lib/browser/components/Default404.js' {
  declare module.exports: $Exports<'react-static/lib/browser/components/Default404'>;
}
declare module 'react-static/lib/browser/components/Root.js' {
  declare module.exports: $Exports<'react-static/lib/browser/components/Root'>;
}
declare module 'react-static/lib/browser/components/RouteData.js' {
  declare module.exports: $Exports<'react-static/lib/browser/components/RouteData'>;
}
declare module 'react-static/lib/browser/components/Routes.js' {
  declare module.exports: $Exports<'react-static/lib/browser/components/Routes'>;
}
declare module 'react-static/lib/browser/components/SiteData.js' {
  declare module.exports: $Exports<'react-static/lib/browser/components/SiteData'>;
}
declare module 'react-static/lib/browser/context/routePathContext.js' {
  declare module.exports: $Exports<'react-static/lib/browser/context/routePathContext'>;
}
declare module 'react-static/lib/browser/context/staticInfoContext.js' {
  declare module.exports: $Exports<'react-static/lib/browser/context/staticInfoContext'>;
}
declare module 'react-static/lib/browser/hooks/useBasepath.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/useBasepath'>;
}
declare module 'react-static/lib/browser/hooks/useLocation.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/useLocation'>;
}
declare module 'react-static/lib/browser/hooks/usePrefetch.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/usePrefetch'>;
}
declare module 'react-static/lib/browser/hooks/useRouteData.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/useRouteData'>;
}
declare module 'react-static/lib/browser/hooks/useRoutePath.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/useRoutePath'>;
}
declare module 'react-static/lib/browser/hooks/useSiteData.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/useSiteData'>;
}
declare module 'react-static/lib/browser/hooks/useStaticInfo.js' {
  declare module.exports: $Exports<'react-static/lib/browser/hooks/useStaticInfo'>;
}
declare module 'react-static/lib/browser/index.js' {
  declare module.exports: $Exports<'react-static/lib/browser/index'>;
}
declare module 'react-static/lib/browser/utils/index.js' {
  declare module.exports: $Exports<'react-static/lib/browser/utils/index'>;
}
declare module 'react-static/lib/browser/utils/onLocationChange.js' {
  declare module.exports: $Exports<'react-static/lib/browser/utils/onLocationChange'>;
}
declare module 'react-static/lib/browser/utils/Visibility.js' {
  declare module.exports: $Exports<'react-static/lib/browser/utils/Visibility'>;
}
declare module 'react-static/lib/commands/build.js' {
  declare module.exports: $Exports<'react-static/lib/commands/build'>;
}
declare module 'react-static/lib/commands/bundle.js' {
  declare module.exports: $Exports<'react-static/lib/commands/bundle'>;
}
declare module 'react-static/lib/commands/create.js' {
  declare module.exports: $Exports<'react-static/lib/commands/create'>;
}
declare module 'react-static/lib/commands/export.js' {
  declare module.exports: $Exports<'react-static/lib/commands/export'>;
}
declare module 'react-static/lib/commands/start.js' {
  declare module.exports: $Exports<'react-static/lib/commands/start'>;
}
declare module 'react-static/lib/index.js' {
  declare module.exports: $Exports<'react-static/lib/index'>;
}
declare module 'react-static/lib/index.node.js' {
  declare module.exports: $Exports<'react-static/lib/index.node'>;
}
declare module 'react-static/lib/node/getWebpackConfig.js' {
  declare module.exports: $Exports<'react-static/lib/node/getWebpackConfig'>;
}
declare module 'react-static/lib/node/makePageRoutes.js' {
  declare module.exports: $Exports<'react-static/lib/node/makePageRoutes'>;
}
declare module 'react-static/lib/static/__mocks__/configWithPluginWithOptions.mock.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/configWithPluginWithOptions.mock'>;
}
declare module 'react-static/lib/static/__mocks__/defaultConfigDevelopment.mock.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/defaultConfigDevelopment.mock'>;
}
declare module 'react-static/lib/static/__mocks__/defaultConfigProduction.mock.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/defaultConfigProduction.mock'>;
}
declare module 'react-static/lib/static/__mocks__/pages/404.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/pages/404'>;
}
declare module 'react-static/lib/static/__mocks__/pages/about.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/pages/about'>;
}
declare module 'react-static/lib/static/__mocks__/pages/index.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/pages/index'>;
}
declare module 'react-static/lib/static/__mocks__/static.config.mock.js' {
  declare module.exports: $Exports<'react-static/lib/static/__mocks__/static.config.mock'>;
}
declare module 'react-static/lib/static/buildState.js' {
  declare module.exports: $Exports<'react-static/lib/static/buildState'>;
}
declare module 'react-static/lib/static/cleanProjectFiles.js' {
  declare module.exports: $Exports<'react-static/lib/static/cleanProjectFiles'>;
}
declare module 'react-static/lib/static/clientStats.js' {
  declare module.exports: $Exports<'react-static/lib/static/clientStats'>;
}
declare module 'react-static/lib/static/components/BodyWithMeta.js' {
  declare module.exports: $Exports<'react-static/lib/static/components/BodyWithMeta'>;
}
declare module 'react-static/lib/static/components/HeadWithMeta.js' {
  declare module.exports: $Exports<'react-static/lib/static/components/HeadWithMeta'>;
}
declare module 'react-static/lib/static/components/HtmlWithMeta.js' {
  declare module.exports: $Exports<'react-static/lib/static/components/HtmlWithMeta'>;
}
declare module 'react-static/lib/static/components/Redirect.js' {
  declare module.exports: $Exports<'react-static/lib/static/components/Redirect'>;
}
declare module 'react-static/lib/static/components/RootComponents.js' {
  declare module.exports: $Exports<'react-static/lib/static/components/RootComponents'>;
}
declare module 'react-static/lib/static/copyPublicFiles.js' {
  declare module.exports: $Exports<'react-static/lib/static/copyPublicFiles'>;
}
declare module 'react-static/lib/static/createSharedData.js' {
  declare module.exports: $Exports<'react-static/lib/static/createSharedData'>;
}
declare module 'react-static/lib/static/exportRoute.js' {
  declare module.exports: $Exports<'react-static/lib/static/exportRoute'>;
}
declare module 'react-static/lib/static/exportRoutes.js' {
  declare module.exports: $Exports<'react-static/lib/static/exportRoutes'>;
}
declare module 'react-static/lib/static/exportRoutes.sync.js' {
  declare module.exports: $Exports<'react-static/lib/static/exportRoutes.sync'>;
}
declare module 'react-static/lib/static/exportRoutes.threaded.js' {
  declare module.exports: $Exports<'react-static/lib/static/exportRoutes.threaded'>;
}
declare module 'react-static/lib/static/exportSharedRouteData.js' {
  declare module.exports: $Exports<'react-static/lib/static/exportSharedRouteData'>;
}
declare module 'react-static/lib/static/extractTemplates.js' {
  declare module.exports: $Exports<'react-static/lib/static/extractTemplates'>;
}
declare module 'react-static/lib/static/fetchRoutes.js' {
  declare module.exports: $Exports<'react-static/lib/static/fetchRoutes'>;
}
declare module 'react-static/lib/static/fetchSiteData.js' {
  declare module.exports: $Exports<'react-static/lib/static/fetchSiteData'>;
}
declare module 'react-static/lib/static/generateBrowserPlugins.js' {
  declare module.exports: $Exports<'react-static/lib/static/generateBrowserPlugins'>;
}
declare module 'react-static/lib/static/generateTemplates.js' {
  declare module.exports: $Exports<'react-static/lib/static/generateTemplates'>;
}
declare module 'react-static/lib/static/getConfig.js' {
  declare module.exports: $Exports<'react-static/lib/static/getConfig'>;
}
declare module 'react-static/lib/static/getRouteData.js' {
  declare module.exports: $Exports<'react-static/lib/static/getRouteData'>;
}
declare module 'react-static/lib/static/getRoutes.js' {
  declare module.exports: $Exports<'react-static/lib/static/getRoutes'>;
}
declare module 'react-static/lib/static/plugins.js' {
  declare module.exports: $Exports<'react-static/lib/static/plugins'>;
}
declare module 'react-static/lib/static/webpack/buildProductionBundles.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/buildProductionBundles'>;
}
declare module 'react-static/lib/static/webpack/makeWebpackConfig.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/makeWebpackConfig'>;
}
declare module 'react-static/lib/static/webpack/rules/cssLoader.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/rules/cssLoader'>;
}
declare module 'react-static/lib/static/webpack/rules/fileLoader.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/rules/fileLoader'>;
}
declare module 'react-static/lib/static/webpack/rules/index.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/rules/index'>;
}
declare module 'react-static/lib/static/webpack/rules/jsLoader.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/rules/jsLoader'>;
}
declare module 'react-static/lib/static/webpack/rules/jsLoaderExternal.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/rules/jsLoaderExternal'>;
}
declare module 'react-static/lib/static/webpack/runDevServer.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/runDevServer'>;
}
declare module 'react-static/lib/static/webpack/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/webpack.config.dev'>;
}
declare module 'react-static/lib/static/webpack/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-static/lib/static/webpack/webpack.config.prod'>;
}
declare module 'react-static/lib/utils/binHelper.js' {
  declare module.exports: $Exports<'react-static/lib/utils/binHelper'>;
}
declare module 'react-static/lib/utils/chunkBuilder.js' {
  declare module.exports: $Exports<'react-static/lib/utils/chunkBuilder'>;
}
declare module 'react-static/lib/utils/createIndexPlaceholder.js' {
  declare module.exports: $Exports<'react-static/lib/utils/createIndexPlaceholder'>;
}
declare module 'react-static/lib/utils/index.js' {
  declare module.exports: $Exports<'react-static/lib/utils/index'>;
}
declare module 'react-static/lib/utils/progress.js' {
  declare module.exports: $Exports<'react-static/lib/utils/progress'>;
}
declare module 'react-static/node/index.js' {
  declare module.exports: $Exports<'react-static/node/index'>;
}
declare module 'react-static/setupTests.js' {
  declare module.exports: $Exports<'react-static/setupTests'>;
}
declare module 'react-static/src/bootstrapApp.js' {
  declare module.exports: $Exports<'react-static/src/bootstrapApp'>;
}
declare module 'react-static/src/bootstrapPlugins.js' {
  declare module.exports: $Exports<'react-static/src/bootstrapPlugins'>;
}
declare module 'react-static/src/bootstrapTemplates.js' {
  declare module.exports: $Exports<'react-static/src/bootstrapTemplates'>;
}
declare module 'react-static/src/browser/__tests__/index.test.js' {
  declare module.exports: $Exports<'react-static/src/browser/__tests__/index.test'>;
}
declare module 'react-static/src/browser/components/Default404.js' {
  declare module.exports: $Exports<'react-static/src/browser/components/Default404'>;
}
declare module 'react-static/src/browser/components/Root.js' {
  declare module.exports: $Exports<'react-static/src/browser/components/Root'>;
}
declare module 'react-static/src/browser/components/RouteData.js' {
  declare module.exports: $Exports<'react-static/src/browser/components/RouteData'>;
}
declare module 'react-static/src/browser/components/Routes.js' {
  declare module.exports: $Exports<'react-static/src/browser/components/Routes'>;
}
declare module 'react-static/src/browser/components/SiteData.js' {
  declare module.exports: $Exports<'react-static/src/browser/components/SiteData'>;
}
declare module 'react-static/src/browser/context/routePathContext.js' {
  declare module.exports: $Exports<'react-static/src/browser/context/routePathContext'>;
}
declare module 'react-static/src/browser/context/staticInfoContext.js' {
  declare module.exports: $Exports<'react-static/src/browser/context/staticInfoContext'>;
}
declare module 'react-static/src/browser/hooks/useBasepath.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/useBasepath'>;
}
declare module 'react-static/src/browser/hooks/useLocation.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/useLocation'>;
}
declare module 'react-static/src/browser/hooks/usePrefetch.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/usePrefetch'>;
}
declare module 'react-static/src/browser/hooks/useRouteData.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/useRouteData'>;
}
declare module 'react-static/src/browser/hooks/useRoutePath.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/useRoutePath'>;
}
declare module 'react-static/src/browser/hooks/useSiteData.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/useSiteData'>;
}
declare module 'react-static/src/browser/hooks/useStaticInfo.js' {
  declare module.exports: $Exports<'react-static/src/browser/hooks/useStaticInfo'>;
}
declare module 'react-static/src/browser/index.js' {
  declare module.exports: $Exports<'react-static/src/browser/index'>;
}
declare module 'react-static/src/browser/utils/__tests__/shared.test.js' {
  declare module.exports: $Exports<'react-static/src/browser/utils/__tests__/shared.test'>;
}
declare module 'react-static/src/browser/utils/index.js' {
  declare module.exports: $Exports<'react-static/src/browser/utils/index'>;
}
declare module 'react-static/src/browser/utils/onLocationChange.js' {
  declare module.exports: $Exports<'react-static/src/browser/utils/onLocationChange'>;
}
declare module 'react-static/src/browser/utils/Visibility.js' {
  declare module.exports: $Exports<'react-static/src/browser/utils/Visibility'>;
}
declare module 'react-static/src/commands/build.js' {
  declare module.exports: $Exports<'react-static/src/commands/build'>;
}
declare module 'react-static/src/commands/bundle.js' {
  declare module.exports: $Exports<'react-static/src/commands/bundle'>;
}
declare module 'react-static/src/commands/create.js' {
  declare module.exports: $Exports<'react-static/src/commands/create'>;
}
declare module 'react-static/src/commands/export.js' {
  declare module.exports: $Exports<'react-static/src/commands/export'>;
}
declare module 'react-static/src/commands/start.js' {
  declare module.exports: $Exports<'react-static/src/commands/start'>;
}
declare module 'react-static/src/index.js' {
  declare module.exports: $Exports<'react-static/src/index'>;
}
declare module 'react-static/src/index.node.js' {
  declare module.exports: $Exports<'react-static/src/index.node'>;
}
declare module 'react-static/src/node/getWebpackConfig.js' {
  declare module.exports: $Exports<'react-static/src/node/getWebpackConfig'>;
}
declare module 'react-static/src/node/makePageRoutes.js' {
  declare module.exports: $Exports<'react-static/src/node/makePageRoutes'>;
}
declare module 'react-static/src/static/__mocks__/configWithPluginWithOptions.mock.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/configWithPluginWithOptions.mock'>;
}
declare module 'react-static/src/static/__mocks__/defaultConfigDevelopment.mock.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/defaultConfigDevelopment.mock'>;
}
declare module 'react-static/src/static/__mocks__/defaultConfigProduction.mock.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/defaultConfigProduction.mock'>;
}
declare module 'react-static/src/static/__mocks__/pages/404.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/pages/404'>;
}
declare module 'react-static/src/static/__mocks__/pages/about.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/pages/about'>;
}
declare module 'react-static/src/static/__mocks__/pages/index.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/pages/index'>;
}
declare module 'react-static/src/static/__mocks__/static.config.mock.js' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/static.config.mock'>;
}
declare module 'react-static/src/static/__mocks__/static.config.mock.jsx' {
  declare module.exports: $Exports<'react-static/src/static/__mocks__/static.config.mock'>;
}
declare module 'react-static/src/static/__tests__/getConfig.test.js' {
  declare module.exports: $Exports<'react-static/src/static/__tests__/getConfig.test'>;
}
declare module 'react-static/src/static/__tests__/getRoutes.test.js' {
  declare module.exports: $Exports<'react-static/src/static/__tests__/getRoutes.test'>;
}
declare module 'react-static/src/static/__tests__/webpack.test.js' {
  declare module.exports: $Exports<'react-static/src/static/__tests__/webpack.test'>;
}
declare module 'react-static/src/static/buildState.js' {
  declare module.exports: $Exports<'react-static/src/static/buildState'>;
}
declare module 'react-static/src/static/cleanProjectFiles.js' {
  declare module.exports: $Exports<'react-static/src/static/cleanProjectFiles'>;
}
declare module 'react-static/src/static/clientStats.js' {
  declare module.exports: $Exports<'react-static/src/static/clientStats'>;
}
declare module 'react-static/src/static/components/__tests__/BodyWithMeta.test.js' {
  declare module.exports: $Exports<'react-static/src/static/components/__tests__/BodyWithMeta.test'>;
}
declare module 'react-static/src/static/components/__tests__/HeadWithMeta.test.js' {
  declare module.exports: $Exports<'react-static/src/static/components/__tests__/HeadWithMeta.test'>;
}
declare module 'react-static/src/static/components/__tests__/HtmlWithMeta.test.js' {
  declare module.exports: $Exports<'react-static/src/static/components/__tests__/HtmlWithMeta.test'>;
}
declare module 'react-static/src/static/components/BodyWithMeta.js' {
  declare module.exports: $Exports<'react-static/src/static/components/BodyWithMeta'>;
}
declare module 'react-static/src/static/components/HeadWithMeta.js' {
  declare module.exports: $Exports<'react-static/src/static/components/HeadWithMeta'>;
}
declare module 'react-static/src/static/components/HtmlWithMeta.js' {
  declare module.exports: $Exports<'react-static/src/static/components/HtmlWithMeta'>;
}
declare module 'react-static/src/static/components/Redirect.js' {
  declare module.exports: $Exports<'react-static/src/static/components/Redirect'>;
}
declare module 'react-static/src/static/components/RootComponents.js' {
  declare module.exports: $Exports<'react-static/src/static/components/RootComponents'>;
}
declare module 'react-static/src/static/copyPublicFiles.js' {
  declare module.exports: $Exports<'react-static/src/static/copyPublicFiles'>;
}
declare module 'react-static/src/static/createSharedData.js' {
  declare module.exports: $Exports<'react-static/src/static/createSharedData'>;
}
declare module 'react-static/src/static/exportRoute.js' {
  declare module.exports: $Exports<'react-static/src/static/exportRoute'>;
}
declare module 'react-static/src/static/exportRoutes.js' {
  declare module.exports: $Exports<'react-static/src/static/exportRoutes'>;
}
declare module 'react-static/src/static/exportRoutes.sync.js' {
  declare module.exports: $Exports<'react-static/src/static/exportRoutes.sync'>;
}
declare module 'react-static/src/static/exportRoutes.threaded.js' {
  declare module.exports: $Exports<'react-static/src/static/exportRoutes.threaded'>;
}
declare module 'react-static/src/static/exportSharedRouteData.js' {
  declare module.exports: $Exports<'react-static/src/static/exportSharedRouteData'>;
}
declare module 'react-static/src/static/extractTemplates.js' {
  declare module.exports: $Exports<'react-static/src/static/extractTemplates'>;
}
declare module 'react-static/src/static/fetchRoutes.js' {
  declare module.exports: $Exports<'react-static/src/static/fetchRoutes'>;
}
declare module 'react-static/src/static/fetchSiteData.js' {
  declare module.exports: $Exports<'react-static/src/static/fetchSiteData'>;
}
declare module 'react-static/src/static/generateBrowserPlugins.js' {
  declare module.exports: $Exports<'react-static/src/static/generateBrowserPlugins'>;
}
declare module 'react-static/src/static/generateTemplates.js' {
  declare module.exports: $Exports<'react-static/src/static/generateTemplates'>;
}
declare module 'react-static/src/static/getConfig.js' {
  declare module.exports: $Exports<'react-static/src/static/getConfig'>;
}
declare module 'react-static/src/static/getRouteData.js' {
  declare module.exports: $Exports<'react-static/src/static/getRouteData'>;
}
declare module 'react-static/src/static/getRoutes.js' {
  declare module.exports: $Exports<'react-static/src/static/getRoutes'>;
}
declare module 'react-static/src/static/plugins.js' {
  declare module.exports: $Exports<'react-static/src/static/plugins'>;
}
declare module 'react-static/src/static/webpack/buildProductionBundles.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/buildProductionBundles'>;
}
declare module 'react-static/src/static/webpack/makeWebpackConfig.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/makeWebpackConfig'>;
}
declare module 'react-static/src/static/webpack/rules/cssLoader.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/rules/cssLoader'>;
}
declare module 'react-static/src/static/webpack/rules/fileLoader.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/rules/fileLoader'>;
}
declare module 'react-static/src/static/webpack/rules/index.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/rules/index'>;
}
declare module 'react-static/src/static/webpack/rules/jsLoader.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/rules/jsLoader'>;
}
declare module 'react-static/src/static/webpack/rules/jsLoaderExternal.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/rules/jsLoaderExternal'>;
}
declare module 'react-static/src/static/webpack/runDevServer.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/runDevServer'>;
}
declare module 'react-static/src/static/webpack/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/webpack.config.dev'>;
}
declare module 'react-static/src/static/webpack/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-static/src/static/webpack/webpack.config.prod'>;
}
declare module 'react-static/src/utils/__tests__/chunkBuilder.test.js' {
  declare module.exports: $Exports<'react-static/src/utils/__tests__/chunkBuilder.test'>;
}
declare module 'react-static/src/utils/binHelper.js' {
  declare module.exports: $Exports<'react-static/src/utils/binHelper'>;
}
declare module 'react-static/src/utils/chunkBuilder.js' {
  declare module.exports: $Exports<'react-static/src/utils/chunkBuilder'>;
}
declare module 'react-static/src/utils/createIndexPlaceholder.js' {
  declare module.exports: $Exports<'react-static/src/utils/createIndexPlaceholder'>;
}
declare module 'react-static/src/utils/index.js' {
  declare module.exports: $Exports<'react-static/src/utils/index'>;
}
declare module 'react-static/src/utils/progress.js' {
  declare module.exports: $Exports<'react-static/src/utils/progress'>;
}
declare module 'react-static/templates/basic/src/App.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/App'>;
}
declare module 'react-static/templates/basic/src/components/Router.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/components/Router'>;
}
declare module 'react-static/templates/basic/src/containers/Dynamic.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/containers/Dynamic'>;
}
declare module 'react-static/templates/basic/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/containers/Post'>;
}
declare module 'react-static/templates/basic/src/index.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/index'>;
}
declare module 'react-static/templates/basic/src/pages/404.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/pages/404'>;
}
declare module 'react-static/templates/basic/src/pages/about.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/pages/about'>;
}
declare module 'react-static/templates/basic/src/pages/blog.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/pages/blog'>;
}
declare module 'react-static/templates/basic/src/pages/index.js' {
  declare module.exports: $Exports<'react-static/templates/basic/src/pages/index'>;
}
declare module 'react-static/templates/basic/static.config.js' {
  declare module.exports: $Exports<'react-static/templates/basic/static.config'>;
}
declare module 'react-static/templates/blank/src/App.js' {
  declare module.exports: $Exports<'react-static/templates/blank/src/App'>;
}
declare module 'react-static/templates/blank/src/index.js' {
  declare module.exports: $Exports<'react-static/templates/blank/src/index'>;
}
declare module 'react-static/templates/blank/static.config.js' {
  declare module.exports: $Exports<'react-static/templates/blank/static.config'>;
}
declare module 'react-static/templates/stress-test/src/App.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/App'>;
}
declare module 'react-static/templates/stress-test/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/containers/Post'>;
}
declare module 'react-static/templates/stress-test/src/index.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/index'>;
}
declare module 'react-static/templates/stress-test/src/pages/404.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/pages/404'>;
}
declare module 'react-static/templates/stress-test/src/pages/about.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/pages/about'>;
}
declare module 'react-static/templates/stress-test/src/pages/blog.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/pages/blog'>;
}
declare module 'react-static/templates/stress-test/src/pages/index.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/src/pages/index'>;
}
declare module 'react-static/templates/stress-test/static.config.js' {
  declare module.exports: $Exports<'react-static/templates/stress-test/static.config'>;
}
declare module 'react-static/templates/typescript/static.config.js' {
  declare module.exports: $Exports<'react-static/templates/typescript/static.config'>;
}
